title: Lerntagebuch BAIN 
author: Petra 
email: petra.novak@stud.fhgr.ch
description: > # this means to ignore newlines
  Vorlage für ein Lerntagebuch im Kurs Bibliotheks- und Archivinformatik FS2020

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
