title: Lerntagebuch BAIN HS2021
author: Petra Novak 
email: petra.novak@stud.fhgr.ch
description: Mein Lerntagebuch im Kurs Bibliotheks- und Archivinformatik 

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
